@echo off
chcp 65001 >nul

REM ============================================
REM اسکریپت آپلود خودکار به GitHub
REM ============================================

cd /d "G:\github\parsa\website"

echo.
echo  >>> اولیه‌سازی Git... 
git init
git add .
git commit -m "Initial commit - Nova website with admin panel\n\n- Complete PHP website with JSON database\n- Admin panel with login, settings, messages management\n- Security features: CSRF, rate limiting, password hashing\n- Fixed all bugs and issues\n\nGenerated by Mistral Vibe.\nCo-Authored-By: Mistral Vibe <vibe@mistral.ai>"

echo.
echo  >>> لطفاً ریپازیتوری GitHub رو بسازید و آدرس رو وارد کنید
set /p repo_url=Enter GitHub repository URL (e.g., https://github.com/AnishtayiN/nova-website.git):

echo.
git remote add origin %repo_url%
git branch -M master
echo.
echo  >>> در حال آپلود به GitHub...
git push -u origin master

echo.
echo  >>> آپلود کامل شد!
echo.
pause
